spin_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "goodbye"
trigger = { type = "sqs" }
version = "0.1.0"

[[component]]
id = "itowlsontest"
source = "target/wasm32-wasi/release/guest.wasm"
[component.trigger]
queue_url = "https://sqs.us-west-2.amazonaws.com/177456779558/itowlsontest"
[component.build]
command = "cargo build --target wasm32-wasi --release"
